#!/bin/sh -e

# $Rev: 1186 $

DEV="$1"
IPPARAM="$6"

export PATH=/sbin:/bin:/usr/sbin:/usr/bin
ETC="/etc"
TMP="/tmp"
ROUTEBACK="${TMP}/defaultroute.vmc"

# Make sure we are only being called by a vmc invoked pppd
[ "${IPPARAM}" = "vmc" ] || exit 0

# Ubuntu now manages DNS for us

# now save old default route and replace it with our own
OLDGW="`route -n | awk '{ if ($1 == "0.0.0.0") { print $2 ; exit } }'`"
printf "OLDGW=%s" ${OLDGW} > ${ROUTEBACK}
route delete default gw ${OLDGW}
route add default dev ${DEV}
