#!/bin/sh -e

# $Rev: 1186 $

export PATH=/sbin:/bin:/usr/sbin:/usr/bin
MV=`which mv`
RM=`which rm`
TOUCH=`which touch`
CHMOD=`which chmod`
ETC="/etc"
TMP="/tmp"
RESOLVCONF=$(readlink --canonicalize $ETC/resolv.conf)
BACKRESOLV="$RESOLVCONF.pppd-backup"
VMCCONN="$TMP/vmc-conn.lock"

# Does VMCCONN exists?
test -f "$VMCCONN" || exit 0

# get DNS addresses

if [ -z "${USEPEERDNS}" ] ; then # Use VMC supplied static addresses
	if [ -r "${VMCCONN}" ] ; then
		. "${VMCCONN}" # source it
	fi
else # DNS addresses are passed in env
	:
fi

# Back up resolv.conf
# Other backup file can have been created by other script
if [ ! -f $BACKRESOLV ]
then
      $MV $RESOLVCONF $BACKRESOLV
fi

# create new resolv.conf
cat > $RESOLVCONF <<-EOA
nameserver $DNS1
nameserver $DNS2
EOA

# on Fedora 7 umask leaves /etc/resolv.conf as 0600
$CHMOD 644 $RESOLVCONF

# restart nscd because resolv.conf has changed
if [ -e /var/run/nscd.pid ]; then
      /etc/init.d/nscd restart || true
fi

