#!/bin/bash

function fix_peers(){
	if [ -e /etc/ppp/peers ];then
	   chown :dialout /etc/ppp/peers
	   chmod g+w /etc/ppp/peers
	fi
}

function fix_pap(){
	if [ -e /etc/ppp/pap-secrets ];then
		chown :dialout /etc/ppp/pap-secrets
		chmod g+rw /etc/ppp/pap-secrets
	fi
}

function fix_chap(){ 
        if [ -e /etc/ppp/chap-secrets ];then
	   chown :dialout /etc/ppp/chap-secrets
	   chmod g+rw /etc/ppp/chap-secrets
        fi
}

function fix_chap(){ 
        if [ -e /etc/ppp/chap-secrets ];then
	   chown :dialout /etc/ppp/chap-secrets
	   chmod g+rw /etc/ppp/chap-secrets
        fi
}

function fix_pppd(){ 
        if [ -e /usr/sbin/pppd ];then
	   chown :dialout /usr/sbin/pppd
	   chmod 4754 /usr/sbin/pppd
        fi
}


#function add_icon(){ 
#	uif=/opt/xandros/share/AsusLauncher/simpleui.rc
#	vmc="`grep vmc.desktop ${uif}`"
#	if [ -z "${vmc}" ] ; then
#		cp -p ${uif} ${uif}.vmc.inst
#		/opt/vmc/scripts/add_vmc.pl < ${uif}.vmc.inst > ${uif}	
#		chmod 644 ${uif} 
#	fi
#	pkill -USR1 AsusLauncher
#}

#function tidy_up_previous_install(){
#	# incorrectly marked as config files, 
#        # so no auto removal on update will occur
#	rm -f /etc/udev/rules.d/99-huawei-e220.rules
#	rm -f /etc/udev/rules.d/99-novatel-ovation.rules
#	rm -f /etc/udev/rules.d/99-option-icon.rules
#}

function udev_reload(){
	/sbin/udevcontrol reload_rules
}

function add_dell_mini_icon(){
        DELL_LAUNCHER_DIR="/usr/share/dell-launcher/applications";
	DELL_LAUNCHER_HOME_DIR=".config/dell-launcher/applications";
	APPLICATIONS_DIR="/usr/share/applications";
	VMC="vmc.desktop";
    
	if [[ -d $DELL_LAUNCHER_DIR ]]; then
	    echo "Detected dell-launcher applications directory";
	    echo "Adding vmc icon to dell-launcher bar";
	
	    # copying VMC to DELL_LAUNCHER_DIR
	    cp "$APPLICATIONS_DIR/$VMC" "$DELL_LAUNCHER_DIR/$VMC"
	
	    # copying VMC to DELL_LAUNCHER_HOME_DIR
	    cat /etc/passwd | grep '/bin/bash' | cut -d ':' -f 6 | while read line
	    do
		if [[ -d $line ]]; then
		    app_dir="$line/$DELL_LAUNCHER_HOME_DIR";
		    if [[ -d $app_dir ]]; then
			echo "Installing vmc icon in $app_dir";
			cp "$APPLICATIONS_DIR/$VMC" "$app_dir"
			# Setting right user and group for $VMC file.
			ownership=$(stat -c %U:%G $app_dir);
			chown $ownership "$app_dir/$VMC";
		    fi
		fi
	    done
	fi
} # End add_dell_mini_icon


dpkg-divert --package vodafone-mobile-connect \
            --rename --quiet --add /etc/ppp/peers/wvdial

ln -fs /etc/ppp/peers/wvdial.distrib /etc/ppp/peers/wvdial

fix_peers
fix_pap
fix_chap
fix_pppd

#tidy_up_previous_install
udev_reload

#add_icon
add_dell_mini_icon
