#!/bin/bash

function del_dell_mini_icon(){
        DELL_LAUNCHER_DIR="/usr/share/dell-launcher/applications";
	DELL_LAUNCHER_HOME_DIR=".config/dell-launcher/applications";
	APPLICATIONS_DIR="/usr/share/applications";
	VMC="vmc.desktop";

	if [[ -d $DELL_LAUNCHER_DIR ]]; then
	    echo "Detected dell-launcher applications directory";
	    echo "Deleting vmc icon to dell-launcher bar";

	    # Deleting VMC from DELL_LAUNCHER_DIR                                                                                            
            rm -f "$DELL_LAUNCHER_DIR/$VMC"

	    # Deleting VMC from DELL_LAUNCHER_HOME_DIR
            cat /etc/passwd | grep '/bin/bash' | cut -d ':' -f 6 | while read line
            do
                if [[ -d $line ]]; then
                    app_dir="$line/$DELL_LAUNCHER_HOME_DIR";
                    if [[ -d $app_dir ]]; then
                        echo "Deleting vmc icon from $app_dir";
                        rm -f "$app_dir/$VMC";
                    fi
                fi
            done
	fi
} # End del_dell_mini_icon


rm -f /etc/ppp/peers/wvdial
dpkg-divert --package vodafone-mobile-connect --rename --quiet --remove /etc/ppp/peers/wvdial

rm -rf /usr/bin/vodafone-mobile-connect-card-driver-for-linux*

function unfix_pppd(){
        if [ -e /usr/sbin/pppd ];then
           chown :dip /usr/sbin/pppd
	   chmod 0754 /usr/sbin/pppd
        fi
}

#function del_icon(){
#        uif=/opt/xandros/share/AsusLauncher/simpleui.rc
#        vmc="`grep vmc.desktop ${uif}`"
#        if [ -n "${vmc}" ] ; then
#                cp -p ${uif} ${uif}.vmc.remv
#                /opt/vmc/scripts/del_vmc.pl < ${uif}.vmc.remv > ${uif}
#        fi
#}

unfix_pppd

#del_icon
del_dell_mini_icon