export SP_ENCODING=XML

all: es en fr

en es fr: images index devices_distros
	mkdir -p $(ROOT)/user-$@
	docbook2html manual.$@.xml -o $(ROOT)/user-$@
	(cd $(ROOT)/user-$@ && ln -s ../images .)

images:
	mkdir -p $(ROOT)/images
	cp -R images/* $(ROOT)/images/.

index:
	cp -p index.html $(ROOT)/.

devices_distros:
	cp devices_distros.* $(ROOT)/.

.PHONY: images index devices_distros

