#!/bin/bash

rm -f /etc/ppp/peers/wvdial
dpkg-divert --package vodafone-mobile-connect --rename --quiet --remove /etc/ppp/peers/wvdial

rm -rf /usr/bin/vodafone-mobile-connect-card-driver-for-linux*

function unfix_pppd(){
        if [ -e /usr/sbin/pppd ];then
           chown :dip /usr/sbin/pppd
	   chmod 0754 /usr/sbin/pppd
        fi
}

function del_icon(){
	for uif in /opt/xandros/share/AsusLauncher/simpleui.rc /var/lib/AsusLauncher/simpleui.rc ; do
		if [ -f ${uif} ] ; then
        		vmc="`grep vmc.desktop ${uif}`"
			if [ -n "${vmc}" ] ; then
				cp -p ${uif} ${uif}.vmc.remv
				/opt/vmc/scripts/del_vmc.pl < ${uif}.vmc.remv > ${uif}
			fi
		fi
	done
	pkill -USR1 AsusLauncher
}

unfix_pppd

del_icon
