#!/bin/sh -e

# $Rev: 1186 $

DEV="$1"
RIP="$5"
IPPARAM="$6"

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

ETC="/etc"
TMP="/tmp"

# Make sure we are only being called by a vmc invoked pppd
[ "${IPPARAM}" = "vmc" ] || exit 0

# On EeePC we have resolvconf(8) to manage DNS

# If the default route is not ours, save it and replace with our own
OLDGW="`route -n | awk '{ if ($1 == "0.0.0.0") { print $2 ; exit } }'`"
ROUTEBACK="${TMP}/defaultroute.vmc"
if [ "${OLDGW}" != "${RIP}" ] ; then 
    printf "OLDGW=%s" ${OLDGW} > ${ROUTEBACK}
    route delete default gw ${OLDGW}
    route add default dev ${DEV}
fi

